// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdWmCKbEB_ltv5Ph4bNQCkOSa-UUlB5M',
    appId: '1:45021448541:android:d54632128033cb459440b4',
    messagingSenderId: '45021448541',
    projectId: 'jojma-b7fc7',
    storageBucket: 'jojma-b7fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdswHQkRCGshxpNdnO3HJzLTHuUd1qz34',
    appId: '1:45021448541:ios:bb90b4730bb0af2d9440b4',
    messagingSenderId: '45021448541',
    projectId: 'jojma-b7fc7',
    storageBucket: 'jojma-b7fc7.appspot.com',
    androidClientId: '45021448541-fnfs47f3o01fn62mf9mapuobibkp8qoc.apps.googleusercontent.com',
    iosClientId: '45021448541-4hdmgkvo8m291ih3fgfunakuamlergnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.practica1jhoan',
  );
}
